config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "stars/top" => "stars#top"
  resources :users, only: [:show] # ユーザーマイページへのルーティング
  resources :stars do
    resources :plays, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
  resources :cats
  root 'stars#top'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
class Cat < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :star
end

app/models/play.rb
class Play < ApplicationRecord
  belongs_to :star
  belongs_to :user
  validates_uniqueness_of :star_id, scope: :user_id
end

app/models/star.rb
class Star < ApplicationRecord
    belongs_to :user
    has_many :plays, dependent: :destroy
  has_many :played_users, through: :plays, source: :user
    mount_uploader :image, ImageUploader


    has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniau
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
          
  has_many :stars, dependent: :destroy 
  has_many :plays, dependent: :destroy
  has_many :played_stars, through: :plays, source: :star
  validates :name, presence: true 
  validates :profile, length: { maximum: 200 } 
  def already_played?(star)
    self.plays.exists?(star_id: star.id)
  end   
  
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # deviseコントローラーにストロングパラメータを追加する          
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    # サインアップ時にnameのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
    # アカウント編集の時にnameとprofileのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :image])
  end

end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
    def index
    end
  
    def new
      @cat = Cat.new
    end
  
    def show
      @cat = Cat.find_by(id: params[:id])
    end
  
    def create
      @cat = Cat.new(cat_params)
      params[:cat][:question] ? @cat.question = params[:cat][:question].join("") : false
      if @cat.save
          flash[:notice] = "診断が完了しました"
          redirect_to cat_path(@cat.id)
      else
          redirect_to :action => "new"
      end
    end
  
  private
    def cat_params
        params.require(:cat).permit(:id, question: [])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
        before_action :authenticate_user!
      
        def create
          star = Star.find(params[:star_id])
          comment = star.comments.build(comment_params) #buildを使い、contentとtweet_idの二つを同時に代入
          comment.user_id = current_user.id
          if comment.save
            flash[:success] = "コメントしました"
            redirect_back(fallback_location: root_path) #直前のページにリダイレクト
          else
            flash[:success] = "コメントできませんでした"
            redirect_back(fallback_location: root_path) #直前のページにリダイレクト
          end
        end
      
        private
      
          def comment_params
            params.require(:comment).permit(:content)
          end
      end

app/controllers/plays_controller.rb
class PlaysController < ApplicationController
    def create
        play = current_user.plays.create(star_id: params[:star_id]) #user_idとtweet_idの二つを代入
        redirect_back(fallback_location: root_path)
      end
    
      def destroy
        play = Play.find_by(star_id: params[:star_id], user_id: current_user.id)
        play.destroy
        redirect_back(fallback_location: root_path)
      end
end

app/controllers/stars_controller.rb
class StarsController < ApplicationController

    before_action :authenticate_user!, only: [:new, :create]

    def top
    end

    def index
        @stars = Star.all
        @stars = @stars.page(params[:page]).per(3)
    end

    def new
        @Star = Star.new
      end
    
      def create
        star = Star.new(star_params)
        star.user_id = current_user.id
        if star.save!
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end
    
      def show
        @star = Star.find(params[:id])
        @comments = @star.comments
        @comment = Comment.new
      end

      def edit
        @star = Star.find(params[:id])
      end

      def update
        star = Star.find(params[:id])
        if star.update(star_params)
          redirect_to :action => "show", :id => star.id
        else
          redirect_to :action => "new"
        end
      end

      def destroy
        star = Star.find(params[:id])
        star.destroy
        redirect_to action: :index
      end
    
    
      private
      def star_params
        params.require(:star).permit(:osusume, :sakerubeki, :image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
      @user = User.find(params[:id]) 
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/plays_helper.rb
module PlaysHelper
end

app/helpers/stars_helper.rb
module StarsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cats/index.html.erb
<!DOCTYPE html> <!--　この文章がHTML文章であることを伝える要素です。-->
<html lang="ja"><!--言語の指定-->
    <head><!--ページに表示されない情報(サイトの裏側の設定)-->
        <meta charset="utf-8">
        <title>香水診断スタート</title><!--ブラウザのタブのタイトルを指定-->
    </head>

    <body>
        <header>
            <h1 class="headline">
            <a>sleep</a>
            </h1>
            <ul class="nav-list">
                <li class="nav-list-item">about fragrance</li>
                <li class="nav-list-item"><%= link_to "診断", cats_path, class: "link" %></li>
            </ul>
        </header>

        <div class="start">
            <h6>Are you ready?</h6>
            <%= link_to "診断を始める", new_cat_path, class: "link" %>
        </div>
    </body>

app/views/cats/new.html.erb
    <%= form_for(@cat, class: 'form-horizontal', role: 'form') do |f| %>
        <div class="container-sindan">
            <div class="row">
                <div class="sinndannmei">
                    <p>
                        "今のあなたに"
                        <br>
                        "ぴったりのナイトルーティンを診断"
                    </p>
                </div>    

            <div class="question">
                <div class="question1">
                    <h2 class="q1">
                         Q1
                    </h2>
                    <p>
                        眠れないのはなぜ？
                    </p>
                    <div class="img-container">
                        <img src="./static/img/quiz/Q1.png" alt="画像" class="img-container__img">
                    </div>
                    <div class="col-6">
                        <p>
                            <%= f.check_box :question, {multiple: true}, "1", nil %>疲れてないから
                        </p>
                        <div class="control__indicator">
                        </div>
                    </div>
                    <div class="col-6">
                        <p>
                            <%= f.check_box :question, {multiple: true}, "2", nil %>ハイテンションだから
                        </p>
                    <div class="control__indicator">
                    </div>
                
                <div class="question1">
                    <h2 class="q1">
                        Q2
                    </h2>
                    <p>
                        眠りたい時どんな気持ちになりたい？
                    </p>
                    <div class="img-container">
                    <img src="./static/img/quiz/Q1.png" alt="画像" class="img-container__img">
                    </div>
                    <div class="col-6">
                    <p>
                        <%= f.check_box :question, {multiple: true}, "1", nil %>幸せな気持ち
                    </p>
                    </div>
                    <div class="col-6">
                    <p>
                        <%= f.check_box :question, {multiple: true}, "2", nil %>何も考えずに、落ち着いた気持ち
                    </p>
                </div>
                
                <div class="question1">
                    <h2 class="q1">
                        Q3
                    </h2>
                    <p>
                        眠れないときにしたいことは何？
                    </p>
                    <div class="img-container">
                    <img src="./static/img/quiz/Q1.png" alt="画像" class="img-container__img">
                    </div>
                    <div class="col-6">
                    <p>
                    <%= f.check_box :question, {multiple: true}, "1", nil %>身体を動かす
                    </p>
                    </div>
                    <div class="col-6">
                    <p><%= f.check_box :question, {multiple: true}, "2", nil %>リラックスしたい</p>
                </div>
                </div>    
                    <div class="keka">
                    <a onclick="$(this).closest('form').submit();" href="javascript:void(0);">結果を見る→</a>
                </div>
        </div>
       
<% end %>

app/views/cats/show.html.erb
<div class="intoro">
<h5>診断結果</h5>
<p>あなたにおすすめの寝る前にすること…</p>
</div>
<div class="tweet-container">
<div class="tweet">
    <% if @cat.question == "111" %>
    <h6>夜の散歩</h6>
    <p>疲れてないから眠れない、幸せな気持ちで寝たい、身体を動かすことをしたい</p>
    <p></p>

    <% elsif @cat.question == "112" %>
    <h6>本を読む</h6>
    <p>疲れてないから眠れない、幸せな気持ちで寝たい、リラックスしたい</p>
    <p></p>

    <% elsif @cat.question == "121" %>
    <h6>筋トレ</h6>
    <p>疲れてないから眠れない、何も考えずに、落ち着いた気持ちになりたい、身体を動かすことをしたい</p>
    <p></p>

    <% elsif @cat.question == "122" %>
    <h6>アロマを焚く</h6>
    <p>疲れてないから眠れない、何も考えずに、落ち着いた気持ちになりたい、リラックスしたい</p>
    <p></p>

    <% elsif @cat.question == "211" %>
    <h6>湯船に浸かる</h6>
    <p>ハイテンションだから眠れない、幸せな気持ちで寝たい、身体を動かすことをしたい</p>
    <p></p>

    <% elsif @cat.question == "212" %>
    <h6>音楽を聴く<</h6>
    <p>ハイテンションだから眠れない、幸せな気持ちで寝たい、リラックスしたい</p>
    <p></p>
    <% elsif @cat.question == "221" %>
    <h6>ストレッチ、ヨガ<</h6>
    <p>ハイテンションだから眠れない、何も考えずに、落ち着いた気持ちになりたい、身体を動かすことをしたい</p>
    <p></p>

    <% elsif @cat.question == "222" %>
    <h6>深呼吸、力を抜く<</h6>
    <p>ハイテンションだから眠れない、何も考えずに、落ち着いた気持ちになりたい、リラックスしたいv</p>
    <p></p>

    <% end %>
</div>
<%= link_to "診断へ", cats_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nightroutine</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/5915874518.js" crossorigin="anonymous"></script>  
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
  <div class="header-logo">
    <h1>Nightroutine</h1>
  </div>
  <div class="openbtn"><span></span><span></span><span></span></div>
  <nav id="g-nav">
    <div id="g-nav-list">  
      <ul>
        <li>
        <%= link_to "Top", stars_top_path %>
        </li>    
        <li>
        <%= link_to "診断", new_cat_path %>
        </li>  
        <li>
        <%= link_to "みんなのページ", stars_path %>
        </li> 
         
        <li>
        <% if user_signed_in? %>
              <li>
              <%= link_to "Mypage", user_path(current_user.id) %>
              <li>
              <%= button_to 'Logout', destroy_user_session_path, method: :delete %></li>
              </li>  
              <% else %>
            <li><%= link_to "Signup", new_user_registration_path %></li>
            <li><%= link_to "Login", new_user_session_path %></li>
            <% end %>
        </li>  
      </ul>  
    </div>
  </nav>
</header>
  <main>
    <%= yield %>
  </main>
 </body>
</html>

<script src="https://code.jquery.com/jquery-3.7.0.min.js" integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=" crossorigin="anonymous"></script>
 <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
</body>

</html>


<script>
$(".openbtn").click(function () {
 $(this).toggleClass("active");
 $("#g-nav").toggleClass("panelactive");
});
$("#g-nav a").click(function () {
 $(".openbtn").removeClass("active");
 $("#g-nav").removeClass("panelactive");
});
</script>

app/views/stars/edit.html.erb
<%= form_for @star do |f| %>
    <%= f.label :おすすめ %>
    <%= f.text_field :osusume, :size => 140 %> 
    <%= f.label :避けるべきもの %>
    <%= f.text_field :sakerubeki, :size => 140 %> 
    <%= f.submit "編集する" %>
  <% end %>

app/views/stars/index.html.erb
<div class="mina">
  <h1>みんなのナイトルーティン</h1>
    <div class="mina1">
        一覧ページ
        <%= link_to "新規投稿へ", new_star_path %>
        <% if user_signed_in? %>
          <%= link_to "マイページへ", user_path(current_user.id) %>
        <% end %>
    </div> 
</div>

<div class="stars-container">
  <% @stars.each do |t| %>
    
    <div class="toukou">
    <%= image_tag t.image_url, size: "250x200" if t.user.image? %>
      <%= t.user.email %>
      <%= t.osusume %>
      <%= t.sakerubeki %>
      <%= image_tag t.image_url, size: "250x200" if t.image? %>
      <% if user_signed_in? %>
      <% if current_user.already_played?(t) %>
          <%= button_to star_play_path(id: t.id, star_id: t.id), method: :delete do %>
            <i class="fas fa-heart"></i><%= t.plays.count %>
          <% end %>
      <% else %>
          <%= button_to star_plays_path(id: t.id, star_id: t.id), method: :post do %>
            <i class="far fa-heart"></i><%= t.plays.count %>
          <% end %>
      <% end %>f
  <% else %>
  <i class="far fa-heart"></i><%= t.plays.count %>
  <% end %>
  <% if user_signed_in? && current_user.id == t.user_id %>
  <%= link_to "編集する", edit_star_path(t.id) %>
  <%= button_to "削除する", star_path(t.id), method: :delete %>
<% end %> 
    
  <% end %> 
</div>

app/views/stars/new.html.erb
<h1>Fumiup</h1>
<h3>新規投稿ページ</h3>
<%= form_for @Star do |f| %>
    <div class="field">
        <%= f.label :おすすめ  %>
        <%= f.text_area :osusume, :size => 30 %>
    </div>
    
    <div class="field">
        <%= f.label :避けるべき  %>
        <%= f.text_area :sakerubeki, :size => "30x2" %>
    </div>

    <div class="field">
        <%= f.label :image %>
        <%= f.file_field :image %>
    </div>

    <%= f.submit "投稿する" %>
<% end %>

<%= link_to "一覧に戻る", stars_path %>

app/views/stars/show.html.erb
<h1>Fumiup</h1>
<h3>詳細</h3>
<div class="star">
  <p><%= @star.osusume %></p>
  <p><%= @star.sakerubeki%></p>
  <%= image_tag @star.image_url, size: "250x200" if @star.image? %>
  <p><%= @star.created_at %></p>
    <% if user_signed_in? %>
      <% if current_user.already_played?(@star) %>
        <%= link_to star_play_path(@star), method: :delete do %>
          <i class="fas fa-heart"></i><%= @star.plays.count %>
        <% end %>
      <% else %>
        <%= link_to star_plays_path(@star), method: :post do %>
          <i class="far fa-heart"></i><%= @star.plays.count %>
        <% end %>
      <% end %>
    <% else %>
    <i class="far fa-heart"></i><%= @star.plays.count %>
    <% end %>
  <%= link_to "編集する", edit_star_path(@star.id) %>
</div>

<h2>いいねしたユーザー</h2>
<% @star.played_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>
<div class="comment-wrapper">
  <p>コメント一覧</p>
  <% @comments.each do |c| %>
    <div>
      <%= c.user.email unless c.user.blank? %>
      <br>
      <%= c.content %>
    </div>
      <br>
  <% end %>

  <% if user_signed_in? %>
    <%= form_with(model: [@star, @comment], local: true) do |f| %>
      <%= f.text_area :content %>
      <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
</div>
    
<%= link_to "一覧に戻る", stars_path %>

app/views/stars/top.html.erb
<body>
    <div class="topimage">
        <%= image_tag("top2.jpg", class: "topimg") %>
    </div>
    <div class="about">
        <h1>about</h1>
        <div class="about1">
            <div class="about-text">
                アイウエオアイウエオアイウエオアイウエオアイウエオアイウエオアイウエオアイウエオ</br>
                アイウエオアイウエオアイウエオアイウエオアイウエオアイウエオアイウエオアイウエオ</br>
                アイウエオアイウエオ
            </div>
            <div class="about-image">
                <%= image_tag("cat.jpeg", class: "about-img") %>
            </div>
        </div>
        
         <div class="about1">
            <div class="about-image">
                <%= image_tag("cat.jpeg", class: "about-img") %>
            </div>
            <div class="about-text">
                アイウエオアイウエオアイウエオアイウエオアイウエオアイウエオアイウエオアイウエオ</br>
                アイウエオアイウエオアイウエオアイウエオアイウエオアイウエオアイウエオアイウエオ</br>
                アイウエオアイウエオ
            </div>
            
        </div>
        
    </div>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.4/css/all.css">

    <div id="page_top"><a href="#"></a>
    </div>
<body>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>users#show</h1>
<p>名前 : <%= @user.name %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>

<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>

<h2>ユーザーの投稿一覧</h2>
<% @user.stars.each do |t| %>
  <%= t.user.name %>
  <%= t.osusume %>
<% end %>

<%= link_to "一覧に戻る", stars_path %>

<%= image_tag @user.image_url, size: "250x200" if @user.image? %>